
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}

library(tidyverse)
library(lubridate)
library(readxl)
library(patchwork)
library(dplyr)

```


```{r acceleration}

load_accel <- function(file, deployment){
  read_excel(file) %>%
    mutate(
      DateTime = ymd_hms(DateTime),
      Sum_Acc_G = as.numeric(Sum_Acc_G),
      Month = month(DateTime)
    ) %>%
    select(DateTime, Farm, Sum_Acc_G, Month)
}

acc_cmast_shell <- load_accel("C:/Users/annab/OneDrive/Desktop/CMAST_G(on shell).xlsx", "On Shell")
acc_ward_shell <- load_accel("C:/Users/annab/OneDrive/Desktop/Ward_G(on shell).xlsx", "On Shell")
acc_duml_shell <- load_accel("C:/Users/annab/OneDrive/Desktop/DUML_G(on shell).xlsx", "On Shell")

acc_summer <- bind_rows(
  acc_cmast_shell,
  acc_duml_shell,
  acc_ward_shell
) %>%
  dplyr::filter(Month %in% c(5,6,7,8,9)) %>%
  mutate(Farm = factor(Farm,
                       levels = c("CMAST",
                                  "Ward Creek",
                                  "DUML")))

ggplot(acc_summer,
       aes(x = DateTime,
           y = Sum_Acc_G,
           color = Farm)) +
  geom_line() +
  scale_color_manual(values = c(
    "CMAST" = "#ED665DFF",
    "DUML" = "#729ECEFF",
    "Ward Creek" = "#67BF5CFF"
  )) +
  guides(color = guide_legend(override.aes = list(linewidth = 10))) +
  labs(
    title = "Mechanical Energy Characterized at CMAST, Ward Creek, and DUML",
    x = "Date",
    y = "Total Acceleration (G)",
    color = "Site"
  ) +
  theme_minimal() +
  theme(
  panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
) 

```


```{r do at ward and stump}

# load data
load_do <- function(file, farm){
  read_excel(file) %>%
    mutate(
      DateTime = ymd_hms(DateTime),
      DO = as.numeric(DomgL),
      Farm = farm,
      Month = month(DateTime)
    ) %>%
    select(DateTime, Farm, DO, Temp_C, Month)
}

stump_do  <- load_do("C:/Users/annab/OneDrive/Desktop/Cleaned/StumpSound_DO_Cleaned.xlsx", "Stump Sound")
nelson_do <- load_do("C:/Users/annab/OneDrive/Desktop/Cleaned/Nelson_DO_Cleaned.xlsx", "Nelson Bay")

do_summer <- bind_rows(stump_do, nelson_do) %>%
  dplyr::filter(Month %in% c(5, 6, 7, 8, 9)) %>%
  mutate(Farm = factor(Farm,
                       levels = c("Stump Sound",
                                  "Nelson Bay")))

# plot
ggplot(do_summer,
       aes(x = DateTime, y = DO, color = Farm)) +
  geom_line() +

  scale_color_manual(values = c(
    "Nelson Bay"  = "#AD8BC9FF",
    "Stump Sound" = "#FF9E4AFF"
  )) +

guides(color = guide_legend(override.aes = list(linewidth = 10
  ))) +

  labs(
    title = "Full Summer DO at Stump Sound and Nelson Bay",
    x = "Date",
    y = "DO (mg/L)",
    color = "Site") +

  theme_minimal() +
  theme(
  panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
)

```

```{r}

vline_df <- data.frame(
  Variable = "DO",
  DateTime = as.POSIXct("2025-06-15")
)

ggplot(do_summer,
       aes(x = DateTime, y = Temp_C, color = Farm)) +
      geom_line() +
  geom_vline(data = vline_df,
             aes(xintercept = DateTime),
             color = "black",
             linewidth = 0.8) +
  
  scale_color_manual(values = c(
    "Nelson Bay"  = "#AD8BC9FF",
    "Stump Sound" = "#FF9E4AFF"
  )) +
  
  labs(
    x = NULL,
    y = NULL,
    color = "Site"
  ) +
  guides(color = guide_legend(override.aes = list(linewidth = 10
  ))) +
  
  theme_minimal() +
  theme(
    panel.border = element_rect(color = "#767676",
                                fill = NA,
                                linewidth = 0.4)
  )

```


 
```{r}

# load data
cmast_do_25 <- read_excel("C:/Users/annab/OneDrive/Desktop/Cleaned/CMAST_DO_Cleaned.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2025,
    OverlayTime = update(DateTime, year = 2000),
    DO = as.numeric(DomgL),
    Temp_C = as.numeric(Temp_C)
  ) %>%
  select(OverlayTime, Year, DO, Temp_C)

cmast_ph_25 <- read_excel("C:/Users/annab/OneDrive/Desktop/Cleaned/CMAST_pH_Cleaned.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2025,
    OverlayTime = update(DateTime, year = 2000),
    pH = as.numeric(pH)
  ) %>%
  select(OverlayTime, Year, pH)

cmast_sal_25 <- read_excel("C:/Users/annab/OneDrive/Desktop/Cleaned/CMAST_Con_Cleaned.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2025,
    OverlayTime = update(DateTime, year = 2000),
    Salinity = as.numeric(Sal_ppt)
  ) %>%
  select(OverlayTime, Year, Salinity)

cmast_precip_25 <- read_excel("C:/Users/annab/OneDrive/Desktop/Cleaned/CMAST_Precip_Cleaned.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2025,
    OverlayTime = update(DateTime, year = 2000),
    Precipitation = as.numeric(Precip_mm)
  ) %>%
  select(OverlayTime, Year, Precipitation)

# 2024
cmast_do_24 <- read_excel("C:/Users/annab/OneDrive/Desktop/DOsensor_2024.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2024,
    OverlayTime = update(DateTime, year = 2000),
    DO = as.numeric(DomgL),
    Temp_C = as.numeric(Temp_C)
  ) %>%
  select(OverlayTime, Year, DO, Temp_C)

cmast_ph_24 <- read_excel("C:/Users/annab/OneDrive/Desktop/pH_2024.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2024,
    OverlayTime = update(DateTime, year = 2000),
    pH = as.numeric(pH)
  ) %>%
  select(OverlayTime, Year, pH)

cmast_sal_24 <- read_excel("C:/Users/annab/OneDrive/Desktop/Salinity_2024.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2024,
    OverlayTime = update(DateTime, year = 2000),
    Salinity = as.numeric(Sal_ppt)
  ) %>%
  select(OverlayTime, Year, Salinity)

cmast_precip_24 <- read_excel("C:/Users/annab/OneDrive/Desktop/Cleaned/Precipdaily_2024.xlsx") %>%
  mutate(DateTime = ymd_hms(DateTime)) %>%
  filter(month(DateTime) %in% c(5,6,7,8,9,10)) %>%
  mutate(
    Year = 2024,
    OverlayTime = update(DateTime, year = 2000),
    Precipitation = as.numeric(Precip_mm)
  ) %>%
  select(OverlayTime, Year, Precipitation)

# combine data
cmast_do  <- bind_rows(cmast_do_24, cmast_do_25)
cmast_ph  <- bind_rows(cmast_ph_24, cmast_ph_25)
cmast_sal <- bind_rows(cmast_sal_24, cmast_sal_25)
cmast_precip <- bind_rows(cmast_precip_24, cmast_precip_25)

# Convert to long format for plotting
do_long <- cmast_do %>%
  pivot_longer(
    cols = c(Temp_C, DO),
    names_to = "Parameter",
    values_to = "Value"
  ) %>%
  mutate(
    Parameter = recode(Parameter,
                       Temp_C = "Temperature",
                       DO = "Dissolved Oxygen")
  )

ph_long <- cmast_ph %>%
  mutate(Parameter = "pH", Value = pH) %>%
  select(OverlayTime, Year, Parameter, Value)

sal_long <- cmast_sal %>%
  mutate(Parameter = "Salinity", Value = Salinity) %>%
  select(OverlayTime, Year, Parameter, Value)

precip_long <- cmast_precip %>%
  mutate(Parameter = "Precipitation", Value = Precipitation) %>%
  select(OverlayTime, Year, Parameter, Value)

cmast_all <- bind_rows(do_long, ph_long, sal_long, precip_long)

cmast_all$Parameter <- factor(
  cmast_all$Parameter,
  levels = c("Temperature", "Dissolved Oxygen", "Precipitation", "pH", "Salinity")
)

cmast_all <- cmast_all %>%
  mutate(
    Parameter_short = recode(Parameter,
                             "Dissolved Oxygen" = "DO",
                             "Temperature" = "Temperature",
                             "Salinity" = "Salinity",
                             "pH" = "pH",
                             "Precipitation" = "Precipitation"),
    ColorGroup = paste0(Parameter_short, " (", Year, ")")
  ) %>%
  mutate(
    ColorGroup = factor(
      ColorGroup,
      levels = c(
        "Temperature (2024)", "Temperature (2025)",
        "DO (2024)", "DO (2025)",
        "Precipitation (2024)", "Precipitation (2025)",
        "pH (2024)", "pH (2025)",
        "Salinity (2024)", "Salinity (2025)"
      )
    )
  )

  color_palette <- c(
    "Temperature (2024)" = "#67BF5CFF", 
    "Temperature (2025)" = "#ED97CAFF",
    "DO (2024)" = "#A8786EFF", 
    "DO (2025)" = "#FF9E4AFF",
    "Precipitation (2024)" = "#AD8BC9FF",
    "Precipitation (2025)" = "#6DCCDAFF",
        "pH (2024)" = "#767676", 
    "pH (2025)" = "#CDCC5DFF",
    "Salinity (2024)" = "#729ECEFF", 
    "Salinity (2025)" = "#ED665DFF"
  )

ggplot(cmast_all,
       aes(x = OverlayTime,
           y = Value,
           color = ColorGroup,
           group = ColorGroup)) +
  geom_line() +
  scale_color_manual(values = color_palette) +
  scale_x_datetime(
  date_breaks = "1 month",
  date_labels = "%b"
) +
  guides(color = guide_legend(override.aes = list(linewidth = 10))) +
  labs(
    x = NULL,
    y = NULL,
    color = "Parameter by Year"
  ) +
  facet_wrap(~ Parameter,
           scales = "free",
           ncol = 2,
           dir = "v") +
  theme_minimal() +
  theme(
  panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
) +
  theme(legend.position = "none")

# ggsave("cmast.jpeg")

```

```{r}

library(ggplot2)

SurvivalSummary$Site <- recode(SurvivalSummary$Site,
                               "DAF" = "DUML",
                               "StumpSound" = "Stump Sound")

AllSites$Site <- recode(AllSites$Site,
                        "DAF" = "DUML",
                        "StumpSound" = "Stump Sound")

SurvivalSummary$Site <- factor(
  SurvivalSummary$Site,
  levels = c("Ward Creek", "Nelson Bay", "DUML", "Stump Sound", "CMAST")
)

AllSites$Site <- factor(
  AllSites$Site,
  levels = c("Ward Creek", "Nelson Bay", "DUML", "Stump Sound", "CMAST")
)

PrettySurvival <- ggplot(SurvivalSummary,
                         aes(x = Date,
                             y = mean_surv,
                             color = Site,
                             group = Site)) +

geom_point(data = AllSites,
           aes(x = Date,
               y = Survivorship,
               color = Site),
           alpha = 0.12,
           size = 3,
           inherit.aes = FALSE) +
  
  # Error bars (mean ± SD)
  geom_errorbar(aes(ymin = mean_surv - sd_surv,
                    ymax = mean_surv + sd_surv),
                width = 5,
                linewidth = 0.9,
                alpha = 0.6) +
  
  # Mean line
  geom_line(linewidth = 1.5) +
  
  # Mean points
  geom_point(size = 3) +
  
  coord_cartesian(ylim = c(20, 100)) +
  
  scale_color_manual(values = c(
  "CMAST" = "#ED665DFF",
  "DUML" = "#729ECEFF",
  "Ward Creek" = "#67BF5CFF",
  "Nelson Bay"  = "#AD8BC9FF",
  "Stump Sound" = "#FF9E4AFF"
)) +
  
  labs(x = NULL,
       y = NULL,
       color = "Site") +
  guides(color = guide_legend(override.aes = list(linewidth = 10))) +
  
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b") +
  theme_minimal() +
  theme(
  panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
) 

PrettySurvival

ggsave("survival.jpeg")

```

```{r}

#Library import

library(ggplot2)
library(readr)
library(dplyr)
library(GGally)
library(tidyverse)
library(lubridate)
library(readxl)
library(writexl)
library(tidyr)
library(hms)
library(zoo)
library(grid)
library(patchwork)

#Importing growth data
DAFGrowthSheet <- read_excel("C:/Users/annab/Downloads/Growth_12Nov25Filtered.xlsx", sheet = "DUML")
CMTGrowthSheet <- read_excel("C:/Users/annab/Downloads/Growth_12Nov25Filtered.xlsx", sheet = "CMAST")
WCGrowthSheet <- read_excel("C:/Users/annab/Downloads/Growth_12Nov25Filtered.xlsx", sheet = "Ward Creek")


#Turn the sheets into a  combined and separate dataframe set
DAFGrowth <- as.data.frame(DAFGrowthSheet)
CMTGrowth <- as.data.frame(CMTGrowthSheet)
WCGrowth <- as.data.frame(WCGrowthSheet)

combined_growth <- bind_rows(WCGrowth, CMTGrowth, DAFGrowth)

#Filtering out baby oysters under 60mm
combined_growth_filtered <- combined_growth[combined_growth$L_mm >= 60,]

# Boxplot function:
generate_boxplots <- function(dataframe) {
  # Check if the required columns are present in the dataframe
  if (!all(c("Strain", "Stage", "L_mm") %in% colnames(dataframe))) {
    stop("The dataframe must contain 'Strain', 'Stage', and 'L_mm' columns.")
  }
  
  #Factor stage and strain so they display in proper order
  dataframe$Stage <-factor(dataframe$Stage, levels = c("May", "July", "September"))
  
  dataframe$Stage <- recode(dataframe$Stage,
                               "July" = "Jul",
                            "September" = "Sep"
                  )
  
  dataframe$Site <- recode(dataframe$Site,
                               "Duke Aquafarm" = "DUML")
  
  # Create a box plot for each combination of color and month
  p <- ggplot(dataframe, aes(x = Stage, y = L_mm, fill = Site)) +
    geom_boxplot() +
    scale_fill_manual(values = c("CMAST" = "#ED665DFF", "DUML" = "#729ECEFF", "Ward Creek" = "#67BF5CFF")) +
    labs(x = NULL, y = NULL) +
    facet_grid(.~ Site)  # This line creates separate panels for each unique color
  
  return(p)
}

GrowthSites <- generate_boxplots(combined_growth_filtered)   #[combined_growth_filtered$Strain == 'Triploid',])

GrowthSites +
  theme_minimal() +
  theme(
  panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
) +theme(legend.position = "none")

GrowthSites

ggsave("growth sites.jpeg", plot = GrowthSites)



```

```{r}

#Library import

library(ggplot2)
library(readr)
library(dplyr)
library(GGally)
library(tidyverse)
library(lubridate)
library(readxl)
library(writexl)
library(tidyr)
library(hms)
library(zoo)
library(grid)
library(patchwork)

SurvivorshipSheet <- "C:/Users/annab/OneDrive/Desktop/Bass Mortality S26_2.xlsx"
SurvivorshipSheetWC <- read_excel(SurvivorshipSheet, sheet = "Ward Creek")
SurvivorshipSheetCMT <- read_excel(SurvivorshipSheet, sheet = "CMAST")
SurvivorshipSheetDAF <- read_excel(SurvivorshipSheet, sheet = "Duke Aquafarm")
SurvivorshipSheetStump <- read_excel(SurvivorshipSheet, sheet = "Stump Sound")
SurvivorshipSheetNelson <- read_excel(SurvivorshipSheet, sheet = "Nelson Bay")

SurvivorshipWC <- as.data.frame(SurvivorshipSheetWC)
SurvivorshipCMT <- as.data.frame(SurvivorshipSheetCMT)
SurvivorshipDAF <- as.data.frame(SurvivorshipSheetDAF)
SurvivorshipStump <- as.data.frame(SurvivorshipSheetStump)
SurvivorshipNelson <- as.data.frame(SurvivorshipSheetNelson)

#Setting site and combining dataframes:
SurvivorshipWC$Source <- "Ward Creek"
SurvivorshipCMT$Source <- "CMAST"
SurvivorshipDAF$Source <- "Duke Aquafarm"
SurvivorshipStump$Source <- "Stump Sound"
SurvivorshipNelson$Source <- "Nelson Bay"

SurvivorshipWC$BagTag <- as.character(SurvivorshipWC$BagTag)
SurvivorshipCMT$BagTag <- as.character(SurvivorshipCMT$BagTag)
SurvivorshipDAF$BagTag <- as.character(SurvivorshipDAF$BagTag)
SurvivorshipStump$BagTag <- as.character(SurvivorshipStump$BagTag)
SurvivorshipNelson$BagTag <- as.character(SurvivorshipNelson$BagTag)

#Combining data, binning by month

S_Combined <- bind_rows(SurvivorshipWC, SurvivorshipCMT, SurvivorshipDAF, SurvivorshipStump, SurvivorshipNelson)
S_Combined$Month <- month(S_Combined$Date, label = TRUE)

S_Combined$Strain <- recode(S_Combined$Strain,
                        "New River" = "NR",
                        "Stump Sound" = "SS",
                        "Cedar Island" = "CI")

#Function
Mortality <- function(dframe) {
  splot = ggplot(dframe, aes(x = Month, y = Mortality_Count, fill = Strain)) +  #Swap "Strain" to "Source" as needed
    ylim(0, 15) +     #adjust this as needed to fit data
    geom_boxplot() +
    theme_minimal() +
    labs(x = NULL, y = NULL) +
    scale_fill_manual(values = c("New River (NR)" = "#ED97CAFF", "Triploid" = "#A8786EFF", "Stump Sound (SS)" = "#CDCC5DFF", "Cedar Island (CI)" = "#6DCCDAFF"))+
    facet_grid(.~ Strain)
  
  return(splot)
}

MortCurve <-Mortality(S_Combined[S_Combined$Source == "Duke Aquafarm",])

#ggsave("/home/moviac/Documents/School/Duke/Bass/Winter 2026/PosterFigs/CMASTMortBxes.png", plot = MortCurve, width = 10, height = 5)

MortCurve +
  theme_minimal() +
  theme(
  panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
) 

# ggsave("mortstumpwlegend.jpeg")

Mortality <- function(dframe) {
  ggplot(dframe, aes(x = Month, y = Mortality_Count, fill = Strain)) +
    geom_boxplot() +
    facet_grid(Strain ~ Source) +   # facet by farm/source
    theme_minimal() +
    labs(x = NULL, y = NULL) +
    scale_fill_manual(
      values = c(
        "NR" = "#ED97CAFF",
        "Triploid" = "#A8786EFF",
        "SS" = "#CDCC5DFF",
        "CI" = "#6DCCDAFF"
      )
    )
}

# Use all farms at once
MortCurve <- Mortality(S_Combined)

MortCurve +
  theme(
    panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4)
  ) +
    theme(legend.position = "none")



```
```{r}

S_Filtered <- S_Combined %>%
  dplyr::filter(
    !.data$Source %in% c("Stump Sound", "Nelson Bay"),
    .data$Strain %in% c("NR", "Triploid")
  )

Mortality <- function(dframe) {
  ggplot(dframe, aes(x = Month, y = Mortality_Count, fill = Strain)) +
    geom_boxplot() +
    facet_grid(Strain ~ Source) +
    theme_minimal() +
    labs(x = NULL, y = NULL) +
    scale_fill_manual(
      values = c(
        "NR" = "#ED97CAFF",
        "Triploid" = "#A8786EFF"
      )
    )
}

MortCurve <- Mortality(S_Filtered)

MortCurve +
  theme(
    panel.border = element_rect(color = "#767676", fill = NA, linewidth = 0.4),
    legend.position = "none"
  )

```


